format = """\
[](bg:#030B16 fg:#1C3A5E)\
$os\
$time\
$username\
[](fg:#1C3A5E bg:#3B76F0)\
$directory\
[](fg:#3B76F0 bg:#FCF392)\
$git_branch\
$git_status\
$git_metrics\
[](fg:#FCF392 bg:#030B16)
$character"""

# Disable the blank line at the start of the prompt
add_newline = true

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#1C3A5E"
style_root = "bg:#1C3A5E"
format = '[[  $user ](bg:#1C3A5E fg:#8DFBD2)]($style)'
# format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#1C3A5E"
disabled = false# Disabled by default

[directory]
format = "[   $path ]($style)"
style = "fg:#E4E4E4 bg:#3B76F0"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "  "
style = "fg:#1C3A5E bg:#FCF392"

[git_status]
format = '[$all_status]($style)'
style = "fg:#1C3A5E bg:#FCF392"

[git_metrics]
format = '(([ $added ]($added_style))([ $deleted ]($deleted_style)))'
only_nonzero_diffs = true
added_style = "fg:#1C3A5E bg:#FCF392"
deleted_style = "fg:#1C3A5E bg:#FCF392"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[cmd_duration]
format = "[  $duration ]($style)"
style = "fg:bright-white bg:18"

[character]
success_symbol = "[ ❯](green)"
error_symbol = "[ ❯](red)"
[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[󱑍 $time ](bg:#1C3A5E fg:#8DFBD2)]($style)'
